// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteRbacEndpointData, DeleteRbacEndpointErrors, DeleteRbacEndpointResponses, DeleteRbacPolicyData, DeleteRbacPolicyErrors, DeleteRbacPolicyResponses, DeleteRbacResourceGroupData, DeleteRbacResourceGroupErrors, DeleteRbacResourceGroupResponses, DeleteRbacRoleData, DeleteRbacRoleErrors, DeleteRbacRoleResponses, DeleteRbacUserData, DeleteRbacUserErrors, DeleteRbacUserResponses, DeleteUsersUserData, DeleteUsersUserErrors, DeleteUsersUserResponses, GetRbacEndpointData, GetRbacEndpointErrors, GetRbacEndpointResponses, GetRbacListResourceGroupsData, GetRbacListResourceGroupsErrors, GetRbacListResourceGroupsResponses, GetRbacListRolesData, GetRbacListRolesErrors, GetRbacListRolesResponses, GetRbacPolicyData, GetRbacPolicyErrors, GetRbacPolicyResponses, GetRbacResourceGroupData, GetRbacResourceGroupErrors, GetRbacResourceGroupResponses, GetRbacRoleData, GetRbacRoleErrors, GetRbacRoleResponses, GetRbacUserData, GetRbacUserErrors, GetRbacUserResponses, GetUsersListData, GetUsersListErrors, GetUsersListResponses, GetUsersMeData, GetUsersMeErrors, GetUsersMeResponses, GetUsersUserData, GetUsersUserErrors, GetUsersUserResponses, HeadRbacResourceGroupData, HeadRbacResourceGroupErrors, HeadRbacResourceGroupResponses, HeadRbacRoleData, HeadRbacRoleErrors, HeadRbacRoleResponses, HeadUsersUserData, HeadUsersUserErrors, HeadUsersUserResponses, PatchUsersMeData, PatchUsersMeErrors, PatchUsersMeResponses, PatchUsersUserData, PatchUsersUserErrors, PatchUsersUserResponses, PostRbacEndpointData, PostRbacEndpointErrors, PostRbacEndpointResponses, PostRbacPolicyData, PostRbacPolicyErrors, PostRbacPolicyResponses, PostRbacResourceGroupData, PostRbacResourceGroupErrors, PostRbacResourceGroupResponses, PostRbacRoleData, PostRbacRoleErrors, PostRbacRoleResponses, PostRbacUserData, PostRbacUserErrors, PostRbacUserResponses, PostUsersUserData, PostUsersUserErrors, PostUsersUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Delete User
 *
 * Delete an existing user.
 */
export const deleteUsersUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUsersUserData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteUsersUserResponses, DeleteUsersUserErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/users/user',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get User Information
 *
 * Retrieve information about a specific user.
 */
export const getUsersUser = <ThrowOnError extends boolean = false>(options: Options<GetUsersUserData, ThrowOnError>) => {
    return (options.client ?? client).get<GetUsersUserResponses, GetUsersUserErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/users/user',
        ...options
    });
};

/**
 * Check User Existence
 *
 * Check if a specific user exists.
 */
export const headUsersUser = <ThrowOnError extends boolean = false>(options: Options<HeadUsersUserData, ThrowOnError>) => {
    return (options.client ?? client).head<HeadUsersUserResponses, HeadUsersUserErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/users/user',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Update User Information
 *
 * Update information for an existing user. Only provided fields will be updated.
 */
export const patchUsersUser = <ThrowOnError extends boolean = false>(options: Options<PatchUsersUserData, ThrowOnError>) => {
    return (options.client ?? client).patch<PatchUsersUserResponses, PatchUsersUserErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/users/user',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Create New User
 *
 * Create a new user.
 */
export const postUsersUser = <ThrowOnError extends boolean = false>(options: Options<PostUsersUserData, ThrowOnError>) => {
    return (options.client ?? client).post<PostUsersUserResponses, PostUsersUserErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/users/user',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List All Users
 *
 * Retrieve a list of all users.
 */
export const getUsersList = <ThrowOnError extends boolean = false>(options?: Options<GetUsersListData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUsersListResponses, GetUsersListErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/users/list',
        ...options
    });
};

/**
 * Get Current User Information
 *
 * Retrieve information about the currently authenticated user.
 */
export const getUsersMe = <ThrowOnError extends boolean = false>(options?: Options<GetUsersMeData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUsersMeResponses, GetUsersMeErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/users/me',
        ...options
    });
};

/**
 * Update Current User Information
 *
 * Update information for the currently authenticated user. Only provided fields will be updated.
 */
export const patchUsersMe = <ThrowOnError extends boolean = false>(options: Options<PatchUsersMeData, ThrowOnError>) => {
    return (options.client ?? client).patch<PatchUsersMeResponses, PatchUsersMeErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/users/me',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List All Roles
 *
 * Retrieve a list of all roles in the system.
 */
export const getRbacListRoles = <ThrowOnError extends boolean = false>(options?: Options<GetRbacListRolesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetRbacListRolesResponses, GetRbacListRolesErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/list-roles',
        ...options
    });
};

/**
 * Delete Role
 *
 * Delete role from the system.
 */
export const deleteRbacRole = <ThrowOnError extends boolean = false>(options: Options<DeleteRbacRoleData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteRbacRoleResponses, DeleteRbacRoleErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/role',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get assigned users for role
 *
 * Retrieve a list of users assigned to a specific role.
 */
export const getRbacRole = <ThrowOnError extends boolean = false>(options: Options<GetRbacRoleData, ThrowOnError>) => {
    return (options.client ?? client).get<GetRbacRoleResponses, GetRbacRoleErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/role',
        ...options
    });
};

/**
 * Check Role Existence
 *
 * Check if a specific role exists in the system.
 */
export const headRbacRole = <ThrowOnError extends boolean = false>(options: Options<HeadRbacRoleData, ThrowOnError>) => {
    return (options.client ?? client).head<HeadRbacRoleResponses, HeadRbacRoleErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/role',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Create New Role
 *
 * Create a new role in the system.
 */
export const postRbacRole = <ThrowOnError extends boolean = false>(options: Options<PostRbacRoleData, ThrowOnError>) => {
    return (options.client ?? client).post<PostRbacRoleResponses, PostRbacRoleErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/role',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Remove Role from User
 *
 * Remove role from user.
 */
export const deleteRbacUser = <ThrowOnError extends boolean = false>(options: Options<DeleteRbacUserData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteRbacUserResponses, DeleteRbacUserErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/user',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Roles Assigned to User
 *
 * Retrieve a list of roles assigned to a specific user.
 */
export const getRbacUser = <ThrowOnError extends boolean = false>(options: Options<GetRbacUserData, ThrowOnError>) => {
    return (options.client ?? client).get<GetRbacUserResponses, GetRbacUserErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/user',
        ...options
    });
};

/**
 * Assign Roles to User
 *
 * Assign role to a specific user.
 */
export const postRbacUser = <ThrowOnError extends boolean = false>(options: Options<PostRbacUserData, ThrowOnError>) => {
    return (options.client ?? client).post<PostRbacUserResponses, PostRbacUserErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/user',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List All Resource Groups
 *
 * Retrieve a list of all resource groups in the system.
 */
export const getRbacListResourceGroups = <ThrowOnError extends boolean = false>(options?: Options<GetRbacListResourceGroupsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetRbacListResourceGroupsResponses, GetRbacListResourceGroupsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/list-resource-groups',
        ...options
    });
};

/**
 * Delete Resource Group
 *
 * Delete an existing resource group.
 */
export const deleteRbacResourceGroup = <ThrowOnError extends boolean = false>(options: Options<DeleteRbacResourceGroupData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteRbacResourceGroupResponses, DeleteRbacResourceGroupErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/resource-group',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Endpoints Assigned to Resource Group
 *
 * Retrieve a list of endpoints assigned to a specific resource group.
 */
export const getRbacResourceGroup = <ThrowOnError extends boolean = false>(options: Options<GetRbacResourceGroupData, ThrowOnError>) => {
    return (options.client ?? client).get<GetRbacResourceGroupResponses, GetRbacResourceGroupErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/resource-group',
        ...options
    });
};

/**
 * Check Resource Group Existence
 *
 * Check if a specific resource group exists in the system.
 */
export const headRbacResourceGroup = <ThrowOnError extends boolean = false>(options: Options<HeadRbacResourceGroupData, ThrowOnError>) => {
    return (options.client ?? client).head<HeadRbacResourceGroupResponses, HeadRbacResourceGroupErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/resource-group',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Create New Resource Group
 *
 * Create a new resource group.
 */
export const postRbacResourceGroup = <ThrowOnError extends boolean = false>(options: Options<PostRbacResourceGroupData, ThrowOnError>) => {
    return (options.client ?? client).post<PostRbacResourceGroupResponses, PostRbacResourceGroupErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/resource-group',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Remove Endpoint from Resource Group
 *
 * Remove an endpoint from its assigned resource group.
 */
export const deleteRbacEndpoint = <ThrowOnError extends boolean = false>(options: Options<DeleteRbacEndpointData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteRbacEndpointResponses, DeleteRbacEndpointErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/endpoint',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Resource Group Assigned to Endpoint
 *
 * Retrieve the resource group assigned to a specific endpoint.
 */
export const getRbacEndpoint = <ThrowOnError extends boolean = false>(options: Options<GetRbacEndpointData, ThrowOnError>) => {
    return (options.client ?? client).get<GetRbacEndpointResponses, GetRbacEndpointErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/endpoint',
        ...options
    });
};

/**
 * Assign Endpoint to Resource Group
 *
 * Assign an endpoint to a specific resource group.
 */
export const postRbacEndpoint = <ThrowOnError extends boolean = false>(options: Options<PostRbacEndpointData, ThrowOnError>) => {
    return (options.client ?? client).post<PostRbacEndpointResponses, PostRbacEndpointErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/endpoint',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete RBAC Policy
 *
 * Delete an existing role-based access control (RBAC) policy, if it existed.
 */
export const deleteRbacPolicy = <ThrowOnError extends boolean = false>(options: Options<DeleteRbacPolicyData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteRbacPolicyResponses, DeleteRbacPolicyErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/policy',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List All RBAC Policies
 *
 * Retrieve a list of all role-based access control (RBAC) policies.
 */
export const getRbacPolicy = <ThrowOnError extends boolean = false>(options?: Options<GetRbacPolicyData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetRbacPolicyResponses, GetRbacPolicyErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/policy',
        ...options
    });
};

/**
 * Create New RBAC Policy
 *
 * Create a new role-based access control (RBAC) policy.
 */
export const postRbacPolicy = <ThrowOnError extends boolean = false>(options: Options<PostRbacPolicyData, ThrowOnError>) => {
    return (options.client ?? client).post<PostRbacPolicyResponses, PostRbacPolicyErrors, ThrowOnError>({
        security: [
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/rbac/policy',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
