// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ErrGeneric = {
    error: string;
};

export type ErrField = {
    /**
     * The name of the field that caused the error.
     */
    field: string;
    /**
     * A description of the error related to the field.
     */
    error: string;
};

export type UserResponse = {
    /**
     * The uuid of the user.
     */
    id: string;
    /**
     * The name of the user.
     */
    name: string;
    /**
     * The display name of the user.
     */
    displayName: string;
};

export type UserRequest = {
    /**
     * The uuid of the user to retrieve.
     */
    id: string;
};

export type CreateUser = {
    /**
     * The name of the user to create.
     */
    name: string;
    /**
     * The password for the new user.
     */
    password: string;
    /**
     * The display name for the new user.
     */
    displayName: string;
};

export type PatchUser = {
    /**
     * The uuid of the user to update.
     */
    id: string;
    /**
     * The new name for the user.
     */
    newName?: string;
    /**
     * The new password for the user.
     */
    newPassword?: string;
    /**
     * The new display name for the user.
     */
    newDisplayName?: string;
};

export type PatchMe = {
    /**
     * The new name for the current user.
     */
    newName?: string;
    /**
     * The new password for the current user.
     */
    newPassword?: string;
    /**
     * The new display name for the current user.
     */
    newDisplayName?: string;
};

export type RbacRole = {
    /**
     * The name of the role.
     */
    role: string;
};

export type RbacUserRolesRequest = {
    /**
     * The uuid of the user.
     */
    userId: string;
};

export type RbacPolicy = {
    /**
     * The name of the role. (or "*" for all roles)
     */
    role: string;
    /**
     * The name of the resource group. (or "*" for all resource groups)
     */
    resourceGroup: string;
    /**
     * The allowed permission (e.g., "GET", "POST", "*").
     */
    permission: 'GET' | 'POST' | 'PATCH' | 'DELETE' | 'HEAD' | '*';
};

export type DeleteUsersUserData = {
    body: UserRequest;
    path?: never;
    query?: never;
    url: '/users/user';
};

export type DeleteUsersUserErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteUsersUserError = DeleteUsersUserErrors[keyof DeleteUsersUserErrors];

export type DeleteUsersUserResponses = {
    /**
     * User deleted successfully. Returns the deleted user.
     */
    200: UserResponse;
};

export type DeleteUsersUserResponse = DeleteUsersUserResponses[keyof DeleteUsersUserResponses];

export type GetUsersUserData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The uuid of the user to retrieve.
         */
        userId: string;
    };
    url: '/users/user';
};

export type GetUsersUserErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetUsersUserError = GetUsersUserErrors[keyof GetUsersUserErrors];

export type GetUsersUserResponses = {
    /**
     * Successful response with user information.
     */
    200: UserResponse;
};

export type GetUsersUserResponse = GetUsersUserResponses[keyof GetUsersUserResponses];

export type HeadUsersUserData = {
    body: UserRequest;
    path?: never;
    query?: never;
    url: '/users/user';
};

export type HeadUsersUserErrors = {
    /**
     * Bad request.
     */
    400: unknown;
    /**
     * Unauthorized.
     */
    401: unknown;
    /**
     * Forbidden.
     */
    403: unknown;
    /**
     * User does not exist.
     */
    404: unknown;
    /**
     * Internal server error.
     */
    500: unknown;
};

export type HeadUsersUserResponses = {
    /**
     * User exists.
     */
    200: unknown;
};

export type PatchUsersUserData = {
    body: PatchUser;
    path?: never;
    query?: never;
    url: '/users/user';
};

export type PatchUsersUserErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * A user with the given new name already exists.
     */
    409: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PatchUsersUserError = PatchUsersUserErrors[keyof PatchUsersUserErrors];

export type PatchUsersUserResponses = {
    /**
     * User updated successfully.
     */
    200: UserResponse;
};

export type PatchUsersUserResponse = PatchUsersUserResponses[keyof PatchUsersUserResponses];

export type PostUsersUserData = {
    body: CreateUser;
    path?: never;
    query?: never;
    url: '/users/user';
};

export type PostUsersUserErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * A user with the given name already exists.
     */
    409: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostUsersUserError = PostUsersUserErrors[keyof PostUsersUserErrors];

export type PostUsersUserResponses = {
    /**
     * User created successfully.
     */
    201: UserResponse;
};

export type PostUsersUserResponse = PostUsersUserResponses[keyof PostUsersUserResponses];

export type GetUsersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/list';
};

export type GetUsersListErrors = {
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetUsersListResponses = {
    /**
     * Successful response with a list of users.
     */
    200: Array<UserResponse>;
};

export type GetUsersListResponse = GetUsersListResponses[keyof GetUsersListResponses];

export type GetUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetUsersMeErrors = {
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetUsersMeResponses = {
    /**
     * Successful response with current user information.
     */
    200: UserResponse;
};

export type GetUsersMeResponse = GetUsersMeResponses[keyof GetUsersMeResponses];

export type PatchUsersMeData = {
    body: PatchMe;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type PatchUsersMeErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * A user with the given new name already exists.
     */
    409: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PatchUsersMeError = PatchUsersMeErrors[keyof PatchUsersMeErrors];

export type PatchUsersMeResponses = {
    /**
     * Current user updated successfully.
     */
    200: UserResponse;
};

export type PatchUsersMeResponse = PatchUsersMeResponses[keyof PatchUsersMeResponses];

export type GetRbacListRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rbac/list-roles';
};

export type GetRbacListRolesErrors = {
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetRbacListRolesResponses = {
    /**
     * Successful response with a list of roles.
     */
    200: Array<string>;
};

export type GetRbacListRolesResponse = GetRbacListRolesResponses[keyof GetRbacListRolesResponses];

export type DeleteRbacRoleData = {
    body: RbacRole;
    path?: never;
    query?: never;
    url: '/rbac/role';
};

export type DeleteRbacRoleErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The resource group could not be deleted due to internal restrictions.
     */
    409: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteRbacRoleError = DeleteRbacRoleErrors[keyof DeleteRbacRoleErrors];

export type DeleteRbacRoleResponses = {
    /**
     * Roles deleted successfully.
     */
    200: unknown;
};

export type GetRbacRoleData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The name of the role.
         */
        role: string;
    };
    url: '/rbac/role';
};

export type GetRbacRoleErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetRbacRoleError = GetRbacRoleErrors[keyof GetRbacRoleErrors];

export type GetRbacRoleResponses = {
    /**
     * Successful response with a list of users assigned to the role.
     */
    200: Array<string>;
};

export type GetRbacRoleResponse = GetRbacRoleResponses[keyof GetRbacRoleResponses];

export type HeadRbacRoleData = {
    body: RbacRole;
    path?: never;
    query?: never;
    url: '/rbac/role';
};

export type HeadRbacRoleErrors = {
    /**
     * Bad request.
     */
    400: unknown;
    /**
     * Unauthorized.
     */
    401: unknown;
    /**
     * Forbidden.
     */
    403: unknown;
    /**
     * Role does not exist.
     */
    404: unknown;
    /**
     * Internal server error.
     */
    500: unknown;
};

export type HeadRbacRoleResponses = {
    /**
     * Role exists.
     */
    200: unknown;
};

export type PostRbacRoleData = {
    body: RbacRole;
    path?: never;
    query?: never;
    url: '/rbac/role';
};

export type PostRbacRoleErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * A role with the given name already exists.
     */
    409: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostRbacRoleError = PostRbacRoleErrors[keyof PostRbacRoleErrors];

export type PostRbacRoleResponses = {
    /**
     * Role created successfully.
     */
    201: unknown;
};

export type DeleteRbacUserData = {
    body: {
        /**
         * The uuid of the user.
         */
        userId: string;
        /**
         * The name of the role to remove from the user.
         */
        role: string;
    };
    path?: never;
    query?: never;
    url: '/rbac/user';
};

export type DeleteRbacUserErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteRbacUserError = DeleteRbacUserErrors[keyof DeleteRbacUserErrors];

export type DeleteRbacUserResponses = {
    /**
     * Role removed from user successfully.
     */
    200: unknown;
};

export type GetRbacUserData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The uuid of the user.
         */
        userId: string;
    };
    url: '/rbac/user';
};

export type GetRbacUserErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetRbacUserError = GetRbacUserErrors[keyof GetRbacUserErrors];

export type GetRbacUserResponses = {
    /**
     * Successful response with a list of roles assigned to the user.
     */
    200: Array<string>;
};

export type GetRbacUserResponse = GetRbacUserResponses[keyof GetRbacUserResponses];

export type PostRbacUserData = {
    body: {
        /**
         * The uuid of the user.
         */
        userId: string;
        /**
         * The name of the role to assign to the user.
         */
        role: string;
    };
    path?: never;
    query?: never;
    url: '/rbac/user';
};

export type PostRbacUserErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostRbacUserError = PostRbacUserErrors[keyof PostRbacUserErrors];

export type PostRbacUserResponses = {
    /**
     * Role assigned to user successfully or role was already assigned.
     */
    201: unknown;
};

export type GetRbacListResourceGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rbac/list-resource-groups';
};

export type GetRbacListResourceGroupsErrors = {
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetRbacListResourceGroupsResponses = {
    /**
     * Successful response with a list of resource groups.
     */
    200: Array<string>;
};

export type GetRbacListResourceGroupsResponse = GetRbacListResourceGroupsResponses[keyof GetRbacListResourceGroupsResponses];

export type DeleteRbacResourceGroupData = {
    body: {
        /**
         * The name of the resource group.
         */
        resourceGroup: string;
    };
    path?: never;
    query?: never;
    url: '/rbac/resource-group';
};

export type DeleteRbacResourceGroupErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteRbacResourceGroupError = DeleteRbacResourceGroupErrors[keyof DeleteRbacResourceGroupErrors];

export type DeleteRbacResourceGroupResponses = {
    /**
     * Resource group deleted successfully.
     */
    200: unknown;
};

export type GetRbacResourceGroupData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The name of the resource group.
         */
        resourceGroup: string;
    };
    url: '/rbac/resource-group';
};

export type GetRbacResourceGroupErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetRbacResourceGroupError = GetRbacResourceGroupErrors[keyof GetRbacResourceGroupErrors];

export type GetRbacResourceGroupResponses = {
    /**
     * Successful response with a list of roles assigned to the resource group.
     */
    200: Array<string>;
};

export type GetRbacResourceGroupResponse = GetRbacResourceGroupResponses[keyof GetRbacResourceGroupResponses];

export type HeadRbacResourceGroupData = {
    body: {
        /**
         * The name of the resource group.
         */
        resourceGroup: string;
    };
    path?: never;
    query?: never;
    url: '/rbac/resource-group';
};

export type HeadRbacResourceGroupErrors = {
    /**
     * Bad request.
     */
    400: unknown;
    /**
     * Unauthorized.
     */
    401: unknown;
    /**
     * Forbidden.
     */
    403: unknown;
    /**
     * Resource group does not exist.
     */
    404: unknown;
    /**
     * Internal server error.
     */
    500: unknown;
};

export type HeadRbacResourceGroupResponses = {
    /**
     * Resource group exists.
     */
    200: unknown;
};

export type PostRbacResourceGroupData = {
    body: {
        /**
         * The name of the resource group.
         */
        resourceGroup: string;
    };
    path?: never;
    query?: never;
    url: '/rbac/resource-group';
};

export type PostRbacResourceGroupErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * A resource group with the given name already exists.
     */
    409: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostRbacResourceGroupError = PostRbacResourceGroupErrors[keyof PostRbacResourceGroupErrors];

export type PostRbacResourceGroupResponses = {
    /**
     * Resource group created successfully.
     */
    201: unknown;
};

export type DeleteRbacEndpointData = {
    body: {
        /**
         * The endpoint to remove from its resource group.
         */
        endpoint: string;
        /**
         * The name of the resource group.
         */
        resourceGroup: string;
    };
    path?: never;
    query?: never;
    url: '/rbac/endpoint';
};

export type DeleteRbacEndpointErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteRbacEndpointError = DeleteRbacEndpointErrors[keyof DeleteRbacEndpointErrors];

export type DeleteRbacEndpointResponses = {
    /**
     * Endpoint removed from resource group successfully.
     */
    200: unknown;
};

export type GetRbacEndpointData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The endpoint to query.
         */
        endpoint: string;
    };
    url: '/rbac/endpoint';
};

export type GetRbacEndpointErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetRbacEndpointError = GetRbacEndpointErrors[keyof GetRbacEndpointErrors];

export type GetRbacEndpointResponses = {
    /**
     * Successful response with the resource group assigned to the endpoint. Empty array if endpoint is not assigned to any resource group.
     */
    200: Array<string>;
};

export type GetRbacEndpointResponse = GetRbacEndpointResponses[keyof GetRbacEndpointResponses];

export type PostRbacEndpointData = {
    body: {
        /**
         * The name of the resource group.
         */
        resourceGroup: string;
        /**
         * The endpoint to assign to the resource group.
         */
        endpoint: string;
    };
    path?: never;
    query?: never;
    url: '/rbac/endpoint';
};

export type PostRbacEndpointErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostRbacEndpointError = PostRbacEndpointErrors[keyof PostRbacEndpointErrors];

export type PostRbacEndpointResponses = {
    /**
     * Endpoint assigned to resource group successfully or was already assigned.
     */
    201: unknown;
};

export type DeleteRbacPolicyData = {
    body: RbacPolicy;
    path?: never;
    query?: never;
    url: '/rbac/policy';
};

export type DeleteRbacPolicyErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteRbacPolicyError = DeleteRbacPolicyErrors[keyof DeleteRbacPolicyErrors];

export type DeleteRbacPolicyResponses = {
    /**
     * RBAC policy deleted successfully.
     */
    200: unknown;
};

export type GetRbacPolicyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rbac/policy';
};

export type GetRbacPolicyErrors = {
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetRbacPolicyResponses = {
    /**
     * Successful response with a list of RBAC policies.
     */
    200: Array<RbacPolicy>;
};

export type GetRbacPolicyResponse = GetRbacPolicyResponses[keyof GetRbacPolicyResponses];

export type PostRbacPolicyData = {
    body: RbacPolicy;
    path?: never;
    query?: never;
    url: '/rbac/policy';
};

export type PostRbacPolicyErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * One or more fields were invalid.
     */
    404: {
        errors?: Array<ErrField>;
    };
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostRbacPolicyError = PostRbacPolicyErrors[keyof PostRbacPolicyErrors];

export type PostRbacPolicyResponses = {
    /**
     * RBAC policy created successfully.
     */
    201: unknown;
};
