// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.yml` | (string & {});
};

export type CreateTaskRequest = {
    /**
     * Task source in the form namespace:name/interface/function@<hash|tag>.
     */
    source: string;
    /**
     * Parameters passed to the task.
     */
    params?: Array<unknown>;
    /**
     * Argument list used to invoke the task.
     */
    args?: Array<string>;
    /**
     * Environment variables supplied to the task.
     */
    env?: Array<EnvironmentVariable>;
    /**
     * Callback URL invoked on task completion.
     */
    callback?: string;
    /**
     * Duration to retain the task after completion.
     */
    retention?: string;
    /**
     * Maximum number of retries before the task is moved to state archived
     */
    retries?: number;
};

export type Task = {
    /**
     * Unique identifier for the task.
     */
    id: string;
    /**
     * Task source in the form namespace:name/interface/function@<hash|tag>.
     */
    source: string;
    /**
     * Parameters passed to the task.
     */
    params?: Array<unknown>;
    /**
     * Argument list used to invoke the task.
     */
    args?: Array<string>;
    /**
     * Environment variables supplied to the task.
     */
    env?: Array<EnvironmentVariable>;
    /**
     * Callback URL invoked on task completion.
     */
    callback?: string;
    /**
     * Duration to retain the task after completion.
     */
    retention?: string;
    /**
     * Maximum number of retries before the task is moved to state archived
     */
    retries?: number;
    status: TaskStatus;
};

export type TaskStatus = {
    /**
     * Current retry count.
     */
    retries: number;
    /**
     * Current status of the task.
     */
    state: string;
    /**
     * Result payload of the task.
     */
    result_payload?: string;
    /**
     * Error message from the last failure.
     */
    last_error?: string;
    /**
     * Time of the last failure.
     */
    last_failed_at?: string;
    /**
     * Time the task is scheduled for processing next.
     */
    next_process_at?: string;
    /**
     * Time the task finished processing.
     */
    completed_at?: string;
};

export type TaskLog = {
    /**
     * Time the log entry was created.
     */
    timestamp: string;
    /**
     * Log level (e.g., debug, info, warn, error, fatal).
     */
    level: string;
    /**
     * Component that issued the log entry.
     */
    issuer: string;
    /**
     * Log message content.
     */
    message: string;
};

export type EnvironmentVariable = {
    /**
     * Environment variable name.
     */
    key: string;
    /**
     * Environment variable value.
     */
    value: string;
};

export type ErrGeneric = {
    error: string;
};

export type ErrField = {
    /**
     * The name of the field that caused the error.
     */
    field: string;
    /**
     * A description of the error related to the field.
     */
    error: string;
};

export type UserResponse = {
    /**
     * The name of the user.
     */
    name: string;
    /**
     * The display name of the user.
     */
    displayName: string;
    /**
     * Roles assigned to the user.
     */
    roles?: Array<string>;
};

export type PutUserRequest = {
    /**
     * The password for the new user.
     */
    password: string;
    /**
     * The display name for the new user.
     */
    displayName: string;
    /**
     * Roles assigned to the new user.
     */
    roles?: Array<string>;
};

export type PatchUser = {
    /**
     * The password for the user.
     */
    password?: string;
    /**
     * The display name for the user.
     */
    displayName?: string;
    /**
     * Roles assigned to the user.
     */
    roles?: Array<string>;
};

export type PatchMe = {
    /**
     * The password for the current user.
     */
    password?: string;
    /**
     * The display name for the current user.
     */
    displayName?: string;
    /**
     * Roles assigned to the current user.
     */
    roles?: Array<string>;
};

export type RbacPolicy = {
    /**
     * The name of the role. (or "*" for all roles)
     */
    role: string;
    /**
     * The name of the resource group. (or "*" for all resource groups)
     */
    resourceGroup: string;
    /**
     * The allowed HTTP method (e.g., "GET", "POST", "*").
     */
    method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | '*';
};

export type RoleResource = {
    /**
     * The role name.
     */
    name: string;
    /**
     * Usernames assigned to this role.
     */
    users: Array<string>;
};

export type PutRoleRequest = {
    /**
     * Usernames assigned to this role.
     */
    users: Array<string>;
};

export type ResourceGroupResource = {
    /**
     * The resource group name.
     */
    name: string;
    /**
     * Endpoints assigned to this resource group.
     */
    endpoints: Array<string>;
};

export type PutResourceGroupRequest = {
    /**
     * Endpoints assigned to this resource group.
     */
    endpoints: Array<string>;
};

/**
 * Metadata of an artifact version.
 */
export type Artifact = {
    /**
     * Namespace of the artifact.
     */
    namespace: string;
    /**
     * Name of the artifact.
     */
    name: string;
    /**
     * Version hash of the artifact.
     */
    versionHash: string;
    /**
     * Creation timestamp of the artifact.
     */
    createdAt: string;
    /**
     * Number of times the artifact has been pulled.
     */
    pulls: number;
    /**
     * Tags associated with the artifact.
     */
    tags: Array<string>;
};

export type PatchArtifact = {
    /**
     * Tags to assign to the artifact version. When set, replaces the existing tags.
     */
    tags?: Array<string>;
};

export type UploadArtifactResponse = {
    /**
     * Created version hash.
     */
    versionHash: string;
};

export type GetV1UserData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of users to return.
         */
        limit?: number;
        /**
         * Offset into the user list.
         */
        offset?: number;
        /**
         * Filter by exact username.
         */
        name?: string;
        /**
         * Filter by display name.
         */
        'display-name'?: string;
    };
    url: '/v1/user';
};

export type GetV1UserErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1UserError = GetV1UserErrors[keyof GetV1UserErrors];

export type GetV1UserResponses = {
    /**
     * Successful response with a list of users.
     */
    200: Array<UserResponse>;
};

export type GetV1UserResponse = GetV1UserResponses[keyof GetV1UserResponses];

export type DeleteV1UserByUsernameData = {
    body?: never;
    path: {
        /**
         * Unique name of the user.
         */
        username: string;
    };
    query?: never;
    url: '/v1/user/{username}';
};

export type DeleteV1UserByUsernameErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteV1UserByUsernameError = DeleteV1UserByUsernameErrors[keyof DeleteV1UserByUsernameErrors];

export type DeleteV1UserByUsernameResponses = {
    /**
     * User deleted successfully. Returns the deleted user.
     */
    200: UserResponse;
};

export type DeleteV1UserByUsernameResponse = DeleteV1UserByUsernameResponses[keyof DeleteV1UserByUsernameResponses];

export type GetV1UserByUsernameData = {
    body?: never;
    path: {
        /**
         * Unique name of the user.
         */
        username: string;
    };
    query?: never;
    url: '/v1/user/{username}';
};

export type GetV1UserByUsernameErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1UserByUsernameError = GetV1UserByUsernameErrors[keyof GetV1UserByUsernameErrors];

export type GetV1UserByUsernameResponses = {
    /**
     * Successful response with user information.
     */
    200: UserResponse;
};

export type GetV1UserByUsernameResponse = GetV1UserByUsernameResponses[keyof GetV1UserByUsernameResponses];

export type HeadV1UserByUsernameData = {
    body?: never;
    path: {
        /**
         * Unique name of the user.
         */
        username: string;
    };
    query?: never;
    url: '/v1/user/{username}';
};

export type HeadV1UserByUsernameErrors = {
    /**
     * Bad request.
     */
    400: unknown;
    /**
     * Unauthorized.
     */
    401: unknown;
    /**
     * Forbidden.
     */
    403: unknown;
    /**
     * User does not exist.
     */
    404: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * Internal server error.
     */
    500: unknown;
};

export type HeadV1UserByUsernameError = HeadV1UserByUsernameErrors[keyof HeadV1UserByUsernameErrors];

export type HeadV1UserByUsernameResponses = {
    /**
     * User exists.
     */
    200: unknown;
};

export type PatchV1UserByUsernameData = {
    body: PatchUser;
    path: {
        /**
         * Unique name of the user.
         */
        username: string;
    };
    query?: never;
    url: '/v1/user/{username}';
};

export type PatchV1UserByUsernameErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * User already exists with the new name.
     */
    409: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PatchV1UserByUsernameError = PatchV1UserByUsernameErrors[keyof PatchV1UserByUsernameErrors];

export type PatchV1UserByUsernameResponses = {
    /**
     * User updated successfully.
     */
    200: UserResponse;
};

export type PatchV1UserByUsernameResponse = PatchV1UserByUsernameResponses[keyof PatchV1UserByUsernameResponses];

export type PutV1UserByUsernameData = {
    body: PutUserRequest;
    path: {
        /**
         * Unique name of the user.
         */
        username: string;
    };
    query?: never;
    url: '/v1/user/{username}';
};

export type PutV1UserByUsernameErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * User already exists.
     */
    409: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PutV1UserByUsernameError = PutV1UserByUsernameErrors[keyof PutV1UserByUsernameErrors];

export type PutV1UserByUsernameResponses = {
    /**
     * User created successfully.
     */
    201: UserResponse;
};

export type PutV1UserByUsernameResponse = PutV1UserByUsernameResponses[keyof PutV1UserByUsernameResponses];

export type DeleteV1UserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/user/me';
};

export type DeleteV1UserMeErrors = {
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteV1UserMeError = DeleteV1UserMeErrors[keyof DeleteV1UserMeErrors];

export type DeleteV1UserMeResponses = {
    /**
     * Current user deleted successfully. Returns the deleted user.
     */
    200: UserResponse;
};

export type DeleteV1UserMeResponse = DeleteV1UserMeResponses[keyof DeleteV1UserMeResponses];

export type GetV1UserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/user/me';
};

export type GetV1UserMeErrors = {
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1UserMeError = GetV1UserMeErrors[keyof GetV1UserMeErrors];

export type GetV1UserMeResponses = {
    /**
     * Successful response with current user information.
     */
    200: UserResponse;
};

export type GetV1UserMeResponse = GetV1UserMeResponses[keyof GetV1UserMeResponses];

export type PatchV1UserMeData = {
    body: PatchMe;
    path?: never;
    query?: never;
    url: '/v1/user/me';
};

export type PatchV1UserMeErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * User already exists with the new name.
     */
    409: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PatchV1UserMeError = PatchV1UserMeErrors[keyof PatchV1UserMeErrors];

export type PatchV1UserMeResponses = {
    /**
     * Current user updated successfully.
     */
    200: UserResponse;
};

export type PatchV1UserMeResponse = PatchV1UserMeResponses[keyof PatchV1UserMeResponses];

export type GetV1RbacRoleData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of policies to return.
         */
        limit?: number;
        /**
         * Offset into the policy list.
         */
        offset?: number;
        /**
         * Filter policies by role.
         */
        role?: string;
    };
    url: '/v1/rbac/role';
};

export type GetV1RbacRoleErrors = {
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1RbacRoleError = GetV1RbacRoleErrors[keyof GetV1RbacRoleErrors];

export type GetV1RbacRoleResponses = {
    /**
     * Successful response with a list of roles.
     */
    200: Array<RoleResource>;
};

export type GetV1RbacRoleResponse = GetV1RbacRoleResponses[keyof GetV1RbacRoleResponses];

export type DeleteV1RbacRoleByRoleData = {
    body?: never;
    path: {
        /**
         * The name of the role.
         */
        role: string;
    };
    query?: never;
    url: '/v1/rbac/role/{role}';
};

export type DeleteV1RbacRoleByRoleErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * Tried to delete enclave admin role
     */
    409: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteV1RbacRoleByRoleError = DeleteV1RbacRoleByRoleErrors[keyof DeleteV1RbacRoleByRoleErrors];

export type DeleteV1RbacRoleByRoleResponses = {
    /**
     * Roles deleted successfully.
     */
    200: RoleResource;
};

export type DeleteV1RbacRoleByRoleResponse = DeleteV1RbacRoleByRoleResponses[keyof DeleteV1RbacRoleByRoleResponses];

export type GetV1RbacRoleByRoleData = {
    body?: never;
    path: {
        /**
         * The name of the role.
         */
        role: string;
    };
    query?: never;
    url: '/v1/rbac/role/{role}';
};

export type GetV1RbacRoleByRoleErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1RbacRoleByRoleError = GetV1RbacRoleByRoleErrors[keyof GetV1RbacRoleByRoleErrors];

export type GetV1RbacRoleByRoleResponses = {
    /**
     * Successful response with the role resource.
     */
    200: RoleResource;
};

export type GetV1RbacRoleByRoleResponse = GetV1RbacRoleByRoleResponses[keyof GetV1RbacRoleByRoleResponses];

export type HeadV1RbacRoleByRoleData = {
    body?: never;
    path: {
        /**
         * The name of the role.
         */
        role: string;
    };
    query?: never;
    url: '/v1/rbac/role/{role}';
};

export type HeadV1RbacRoleByRoleErrors = {
    /**
     * Bad request.
     */
    400: unknown;
    /**
     * Unauthorized.
     */
    401: unknown;
    /**
     * Forbidden.
     */
    403: unknown;
    /**
     * Role does not exist.
     */
    404: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * Internal server error.
     */
    500: unknown;
};

export type HeadV1RbacRoleByRoleError = HeadV1RbacRoleByRoleErrors[keyof HeadV1RbacRoleByRoleErrors];

export type HeadV1RbacRoleByRoleResponses = {
    /**
     * Role exists.
     */
    200: unknown;
};

export type PutV1RbacRoleByRoleData = {
    body: PutRoleRequest;
    path: {
        /**
         * The name of the role.
         */
        role: string;
    };
    query?: never;
    url: '/v1/rbac/role/{role}';
};

export type PutV1RbacRoleByRoleErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * Role already exists.
     */
    409: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PutV1RbacRoleByRoleError = PutV1RbacRoleByRoleErrors[keyof PutV1RbacRoleByRoleErrors];

export type PutV1RbacRoleByRoleResponses = {
    /**
     * Role created successfully.
     */
    201: RoleResource;
};

export type PutV1RbacRoleByRoleResponse = PutV1RbacRoleByRoleResponses[keyof PutV1RbacRoleByRoleResponses];

export type GetV1RbacResourceGroupData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of policies to return.
         */
        limit?: number;
        /**
         * Offset into the policy list.
         */
        offset?: number;
        /**
         * Filter policies by role.
         */
        role?: string;
    };
    url: '/v1/rbac/resource-group';
};

export type GetV1RbacResourceGroupErrors = {
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1RbacResourceGroupError = GetV1RbacResourceGroupErrors[keyof GetV1RbacResourceGroupErrors];

export type GetV1RbacResourceGroupResponses = {
    /**
     * Successful response with a list of resource groups.
     */
    200: Array<ResourceGroupResource>;
};

export type GetV1RbacResourceGroupResponse = GetV1RbacResourceGroupResponses[keyof GetV1RbacResourceGroupResponses];

export type DeleteV1RbacResourceGroupByResourceGroupData = {
    body?: never;
    path: {
        /**
         * The name of the resource group.
         */
        resourceGroup: string;
    };
    query?: never;
    url: '/v1/rbac/resource-group/{resourceGroup}';
};

export type DeleteV1RbacResourceGroupByResourceGroupErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteV1RbacResourceGroupByResourceGroupError = DeleteV1RbacResourceGroupByResourceGroupErrors[keyof DeleteV1RbacResourceGroupByResourceGroupErrors];

export type DeleteV1RbacResourceGroupByResourceGroupResponses = {
    /**
     * Resource group deleted successfully.
     */
    200: ResourceGroupResource;
};

export type DeleteV1RbacResourceGroupByResourceGroupResponse = DeleteV1RbacResourceGroupByResourceGroupResponses[keyof DeleteV1RbacResourceGroupByResourceGroupResponses];

export type GetV1RbacResourceGroupByResourceGroupData = {
    body?: never;
    path: {
        /**
         * The name of the resource group.
         */
        resourceGroup: string;
    };
    query?: never;
    url: '/v1/rbac/resource-group/{resourceGroup}';
};

export type GetV1RbacResourceGroupByResourceGroupErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1RbacResourceGroupByResourceGroupError = GetV1RbacResourceGroupByResourceGroupErrors[keyof GetV1RbacResourceGroupByResourceGroupErrors];

export type GetV1RbacResourceGroupByResourceGroupResponses = {
    /**
     * Successful response with the resource group resource.
     */
    200: ResourceGroupResource;
};

export type GetV1RbacResourceGroupByResourceGroupResponse = GetV1RbacResourceGroupByResourceGroupResponses[keyof GetV1RbacResourceGroupByResourceGroupResponses];

export type HeadV1RbacResourceGroupByResourceGroupData = {
    body?: never;
    path: {
        /**
         * The name of the resource group.
         */
        resourceGroup: string;
    };
    query?: never;
    url: '/v1/rbac/resource-group/{resourceGroup}';
};

export type HeadV1RbacResourceGroupByResourceGroupErrors = {
    /**
     * Bad request.
     */
    400: unknown;
    /**
     * Unauthorized.
     */
    401: unknown;
    /**
     * Forbidden.
     */
    403: unknown;
    /**
     * Resource group does not exist.
     */
    404: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * Internal server error.
     */
    500: unknown;
};

export type HeadV1RbacResourceGroupByResourceGroupError = HeadV1RbacResourceGroupByResourceGroupErrors[keyof HeadV1RbacResourceGroupByResourceGroupErrors];

export type HeadV1RbacResourceGroupByResourceGroupResponses = {
    /**
     * Resource group exists.
     */
    200: unknown;
};

export type PutV1RbacResourceGroupByResourceGroupData = {
    body: PutResourceGroupRequest;
    path: {
        /**
         * The name of the resource group.
         */
        resourceGroup: string;
    };
    query?: never;
    url: '/v1/rbac/resource-group/{resourceGroup}';
};

export type PutV1RbacResourceGroupByResourceGroupErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * Resource group already exists.
     */
    409: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PutV1RbacResourceGroupByResourceGroupError = PutV1RbacResourceGroupByResourceGroupErrors[keyof PutV1RbacResourceGroupByResourceGroupErrors];

export type PutV1RbacResourceGroupByResourceGroupResponses = {
    /**
     * Resource group created successfully.
     */
    201: ResourceGroupResource;
};

export type PutV1RbacResourceGroupByResourceGroupResponse = PutV1RbacResourceGroupByResourceGroupResponses[keyof PutV1RbacResourceGroupByResourceGroupResponses];

export type DeleteV1RbacPolicyData = {
    body: RbacPolicy;
    path?: never;
    query?: never;
    url: '/v1/rbac/policy';
};

export type DeleteV1RbacPolicyErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * Tried to delete enclave admin policy
     */
    409: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteV1RbacPolicyError = DeleteV1RbacPolicyErrors[keyof DeleteV1RbacPolicyErrors];

export type DeleteV1RbacPolicyResponses = {
    /**
     * RBAC policy deleted successfully.
     */
    200: unknown;
};

export type GetV1RbacPolicyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of policies to return.
         */
        limit?: number;
        /**
         * Offset into the policy list.
         */
        offset?: number;
        /**
         * Filter policies by role.
         */
        role?: string;
        /**
         * Filter policies by resource group.
         */
        'resource-group'?: string;
        /**
         * Filter policies by HTTP method.
         */
        method?: string;
    };
    url: '/v1/rbac/policy';
};

export type GetV1RbacPolicyErrors = {
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1RbacPolicyError = GetV1RbacPolicyErrors[keyof GetV1RbacPolicyErrors];

export type GetV1RbacPolicyResponses = {
    /**
     * Successful response with a list of RBAC policies.
     */
    200: Array<RbacPolicy>;
};

export type GetV1RbacPolicyResponse = GetV1RbacPolicyResponses[keyof GetV1RbacPolicyResponses];

export type PutV1RbacPolicyData = {
    body: RbacPolicy;
    path?: never;
    query?: never;
    url: '/v1/rbac/policy';
};

export type PutV1RbacPolicyErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * One or more fields were invalid.
     */
    404: {
        errors?: Array<ErrField>;
    };
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PutV1RbacPolicyError = PutV1RbacPolicyErrors[keyof PutV1RbacPolicyErrors];

export type PutV1RbacPolicyResponses = {
    /**
     * RBAC policy created successfully.
     */
    201: unknown;
};

export type PostV1ArtifactRawByNamespaceByNameData = {
    body: Blob | File;
    path: {
        /**
         * Artifact namespace.
         */
        namespace: string;
        /**
         * Artifact name.
         */
        name: string;
    };
    query?: never;
    url: '/v1/artifact/raw/{namespace}/{name}';
};

export type PostV1ArtifactRawByNamespaceByNameErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * Artifact already exists at the provided tag or hash.
     */
    409: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostV1ArtifactRawByNamespaceByNameError = PostV1ArtifactRawByNamespaceByNameErrors[keyof PostV1ArtifactRawByNamespaceByNameErrors];

export type PostV1ArtifactRawByNamespaceByNameResponses = {
    /**
     * Artifact uploaded successfully.
     */
    201: UploadArtifactResponse;
};

export type PostV1ArtifactRawByNamespaceByNameResponse = PostV1ArtifactRawByNamespaceByNameResponses[keyof PostV1ArtifactRawByNamespaceByNameResponses];

export type GetV1ArtifactData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of namespaces to return.
         */
        limit?: number;
        /**
         * Offset into the namespace list.
         */
        offset?: number;
    };
    url: '/v1/artifact';
};

export type GetV1ArtifactErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1ArtifactError = GetV1ArtifactErrors[keyof GetV1ArtifactErrors];

export type GetV1ArtifactResponses = {
    /**
     * Artifact namespace list.
     */
    200: Array<Artifact>;
};

export type GetV1ArtifactResponse = GetV1ArtifactResponses[keyof GetV1ArtifactResponses];

export type GetV1ArtifactByNamespaceData = {
    body?: never;
    path: {
        /**
         * Artifact namespace.
         */
        namespace: string;
    };
    query?: {
        /**
         * Maximum number of artifacts to return.
         */
        limit?: number;
        /**
         * Offset into the artifact list.
         */
        offset?: number;
    };
    url: '/v1/artifact/{namespace}';
};

export type GetV1ArtifactByNamespaceErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1ArtifactByNamespaceError = GetV1ArtifactByNamespaceErrors[keyof GetV1ArtifactByNamespaceErrors];

export type GetV1ArtifactByNamespaceResponses = {
    /**
     * Artifact list for namespace.
     */
    200: Array<Artifact>;
};

export type GetV1ArtifactByNamespaceResponse = GetV1ArtifactByNamespaceResponses[keyof GetV1ArtifactByNamespaceResponses];

export type GetV1ArtifactByNamespaceByNameData = {
    body?: never;
    path: {
        /**
         * Artifact namespace.
         */
        namespace: string;
        /**
         * Artifact name.
         */
        name: string;
    };
    query?: {
        /**
         * Maximum number of versions to return.
         */
        limit?: number;
        /**
         * Offset into the version list.
         */
        offset?: number;
    };
    url: '/v1/artifact/{namespace}/{name}';
};

export type GetV1ArtifactByNamespaceByNameErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1ArtifactByNamespaceByNameError = GetV1ArtifactByNamespaceByNameErrors[keyof GetV1ArtifactByNamespaceByNameErrors];

export type GetV1ArtifactByNamespaceByNameResponses = {
    /**
     * Artifact version list.
     */
    200: Array<Artifact>;
};

export type GetV1ArtifactByNamespaceByNameResponse = GetV1ArtifactByNamespaceByNameResponses[keyof GetV1ArtifactByNamespaceByNameResponses];

export type DeleteV1ArtifactByNamespaceByNameTagByTagData = {
    body?: never;
    path: {
        /**
         * Artifact namespace.
         */
        namespace: string;
        /**
         * Artifact name.
         */
        name: string;
        /**
         * Tag pointing to the desired version.
         */
        tag: string;
    };
    query?: never;
    url: '/v1/artifact/{namespace}/{name}/tag/{tag}';
};

export type DeleteV1ArtifactByNamespaceByNameTagByTagErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteV1ArtifactByNamespaceByNameTagByTagError = DeleteV1ArtifactByNamespaceByNameTagByTagErrors[keyof DeleteV1ArtifactByNamespaceByNameTagByTagErrors];

export type DeleteV1ArtifactByNamespaceByNameTagByTagResponses = {
    /**
     * Artifact deleted successfully.
     */
    200: Artifact;
};

export type DeleteV1ArtifactByNamespaceByNameTagByTagResponse = DeleteV1ArtifactByNamespaceByNameTagByTagResponses[keyof DeleteV1ArtifactByNamespaceByNameTagByTagResponses];

export type GetV1ArtifactByNamespaceByNameTagByTagData = {
    body?: never;
    path: {
        /**
         * Artifact namespace.
         */
        namespace: string;
        /**
         * Artifact name.
         */
        name: string;
        /**
         * Tag pointing to the desired version.
         */
        tag: string;
    };
    query?: never;
    url: '/v1/artifact/{namespace}/{name}/tag/{tag}';
};

export type GetV1ArtifactByNamespaceByNameTagByTagErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1ArtifactByNamespaceByNameTagByTagError = GetV1ArtifactByNamespaceByNameTagByTagErrors[keyof GetV1ArtifactByNamespaceByNameTagByTagErrors];

export type GetV1ArtifactByNamespaceByNameTagByTagResponses = {
    /**
     * Artifact metadata.
     */
    200: Artifact;
};

export type GetV1ArtifactByNamespaceByNameTagByTagResponse = GetV1ArtifactByNamespaceByNameTagByTagResponses[keyof GetV1ArtifactByNamespaceByNameTagByTagResponses];

export type PatchV1ArtifactByNamespaceByNameTagByTagData = {
    body: PatchArtifact;
    path: {
        /**
         * Artifact namespace.
         */
        namespace: string;
        /**
         * Artifact name.
         */
        name: string;
        /**
         * Tag pointing to the desired version.
         */
        tag: string;
    };
    query?: never;
    url: '/v1/artifact/{namespace}/{name}/tag/{tag}';
};

export type PatchV1ArtifactByNamespaceByNameTagByTagErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PatchV1ArtifactByNamespaceByNameTagByTagError = PatchV1ArtifactByNamespaceByNameTagByTagErrors[keyof PatchV1ArtifactByNamespaceByNameTagByTagErrors];

export type PatchV1ArtifactByNamespaceByNameTagByTagResponses = {
    /**
     * Artifact metadata updated successfully.
     */
    200: Artifact;
};

export type PatchV1ArtifactByNamespaceByNameTagByTagResponse = PatchV1ArtifactByNamespaceByNameTagByTagResponses[keyof PatchV1ArtifactByNamespaceByNameTagByTagResponses];

export type DeleteV1ArtifactByNamespaceByNameHashByHashData = {
    body?: never;
    path: {
        /**
         * Artifact namespace.
         */
        namespace: string;
        /**
         * Artifact name.
         */
        name: string;
        /**
         * Version hash of the artifact.
         */
        hash: string;
    };
    query?: never;
    url: '/v1/artifact/{namespace}/{name}/hash/{hash}';
};

export type DeleteV1ArtifactByNamespaceByNameHashByHashErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteV1ArtifactByNamespaceByNameHashByHashError = DeleteV1ArtifactByNamespaceByNameHashByHashErrors[keyof DeleteV1ArtifactByNamespaceByNameHashByHashErrors];

export type DeleteV1ArtifactByNamespaceByNameHashByHashResponses = {
    /**
     * Artifact deleted successfully.
     */
    200: Artifact;
};

export type DeleteV1ArtifactByNamespaceByNameHashByHashResponse = DeleteV1ArtifactByNamespaceByNameHashByHashResponses[keyof DeleteV1ArtifactByNamespaceByNameHashByHashResponses];

export type GetV1ArtifactByNamespaceByNameHashByHashData = {
    body?: never;
    path: {
        /**
         * Artifact namespace.
         */
        namespace: string;
        /**
         * Artifact name.
         */
        name: string;
        /**
         * Version hash of the artifact.
         */
        hash: string;
    };
    query?: never;
    url: '/v1/artifact/{namespace}/{name}/hash/{hash}';
};

export type GetV1ArtifactByNamespaceByNameHashByHashErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1ArtifactByNamespaceByNameHashByHashError = GetV1ArtifactByNamespaceByNameHashByHashErrors[keyof GetV1ArtifactByNamespaceByNameHashByHashErrors];

export type GetV1ArtifactByNamespaceByNameHashByHashResponses = {
    /**
     * Artifact metadata.
     */
    200: Artifact;
};

export type GetV1ArtifactByNamespaceByNameHashByHashResponse = GetV1ArtifactByNamespaceByNameHashByHashResponses[keyof GetV1ArtifactByNamespaceByNameHashByHashResponses];

export type PatchV1ArtifactByNamespaceByNameHashByHashData = {
    body: PatchArtifact;
    path: {
        /**
         * Artifact namespace.
         */
        namespace: string;
        /**
         * Artifact name.
         */
        name: string;
        /**
         * Version hash of the artifact.
         */
        hash: string;
    };
    query?: never;
    url: '/v1/artifact/{namespace}/{name}/hash/{hash}';
};

export type PatchV1ArtifactByNamespaceByNameHashByHashErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PatchV1ArtifactByNamespaceByNameHashByHashError = PatchV1ArtifactByNamespaceByNameHashByHashErrors[keyof PatchV1ArtifactByNamespaceByNameHashByHashErrors];

export type PatchV1ArtifactByNamespaceByNameHashByHashResponses = {
    /**
     * Artifact metadata updated successfully.
     */
    200: Artifact;
};

export type PatchV1ArtifactByNamespaceByNameHashByHashResponse = PatchV1ArtifactByNamespaceByNameHashByHashResponses[keyof PatchV1ArtifactByNamespaceByNameHashByHashResponses];

export type GetV1ArtifactRawByNamespaceByNameTagByTagData = {
    body?: never;
    path: {
        /**
         * Artifact namespace.
         */
        namespace: string;
        /**
         * Artifact name.
         */
        name: string;
        /**
         * Tag pointing to the desired version.
         */
        tag: string;
    };
    query?: never;
    url: '/v1/artifact/raw/{namespace}/{name}/tag/{tag}';
};

export type GetV1ArtifactRawByNamespaceByNameTagByTagErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1ArtifactRawByNamespaceByNameTagByTagError = GetV1ArtifactRawByNamespaceByNameTagByTagErrors[keyof GetV1ArtifactRawByNamespaceByNameTagByTagErrors];

export type GetV1ArtifactRawByNamespaceByNameTagByTagResponses = {
    /**
     * Artifact content.
     */
    200: Blob | File;
};

export type GetV1ArtifactRawByNamespaceByNameTagByTagResponse = GetV1ArtifactRawByNamespaceByNameTagByTagResponses[keyof GetV1ArtifactRawByNamespaceByNameTagByTagResponses];

export type GetV1ArtifactRawByNamespaceByNameHashByHashData = {
    body?: never;
    path: {
        /**
         * Artifact namespace.
         */
        namespace: string;
        /**
         * Artifact name.
         */
        name: string;
        /**
         * Version hash of the artifact.
         */
        hash: string;
    };
    query?: never;
    url: '/v1/artifact/raw/{namespace}/{name}/hash/{hash}';
};

export type GetV1ArtifactRawByNamespaceByNameHashByHashErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1ArtifactRawByNamespaceByNameHashByHashError = GetV1ArtifactRawByNamespaceByNameHashByHashErrors[keyof GetV1ArtifactRawByNamespaceByNameHashByHashErrors];

export type GetV1ArtifactRawByNamespaceByNameHashByHashResponses = {
    /**
     * Artifact content.
     */
    200: Blob | File;
};

export type GetV1ArtifactRawByNamespaceByNameHashByHashResponse = GetV1ArtifactRawByNamespaceByNameHashByHashResponses[keyof GetV1ArtifactRawByNamespaceByNameHashByHashResponses];

export type GetV1TaskData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of tasks to return.
         */
        limit?: number;
        /**
         * Offset for pagination.
         */
        offset?: number;
        /**
         * Filter tasks by state (e.g., ACTIVE).
         */
        state?: string;
    };
    url: '/v1/task';
};

export type GetV1TaskErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1TaskError = GetV1TaskErrors[keyof GetV1TaskErrors];

export type GetV1TaskResponses = {
    /**
     * Successful response with task list.
     */
    200: Array<Task>;
};

export type GetV1TaskResponse = GetV1TaskResponses[keyof GetV1TaskResponses];

export type PostV1TaskData = {
    body: CreateTaskRequest;
    path?: never;
    query?: never;
    url: '/v1/task';
};

export type PostV1TaskErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostV1TaskError = PostV1TaskErrors[keyof PostV1TaskErrors];

export type PostV1TaskResponses = {
    /**
     * Task created successfully.
     */
    201: Task;
};

export type PostV1TaskResponse = PostV1TaskResponses[keyof PostV1TaskResponses];

export type GetV1TaskByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier of the task to retrieve.
         */
        id: string;
    };
    query?: never;
    url: '/v1/task/{id}';
};

export type GetV1TaskByIdErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1TaskByIdError = GetV1TaskByIdErrors[keyof GetV1TaskByIdErrors];

export type GetV1TaskByIdResponses = {
    /**
     * Task details.
     */
    200: Task;
};

export type GetV1TaskByIdResponse = GetV1TaskByIdResponses[keyof GetV1TaskByIdResponses];

export type GetV1TaskByIdLogsData = {
    body?: never;
    path: {
        /**
         * Unique identifier of the task to retrieve logs for.
         */
        id: string;
    };
    query?: {
        /**
         * Filter logs by level.
         */
        level?: string;
        /**
         * Filter logs by issuer.
         */
        issuer?: string;
        /**
         * Start of the time range filter. Must be used with time-range-to and be more recent.
         */
        'time-range-from'?: string;
        /**
         * End of the time range filter. Must be used with time-range-from and be less recent.
         */
        'time-range-to'?: string;
    };
    url: '/v1/task/{id}/logs';
};

export type GetV1TaskByIdLogsErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetV1TaskByIdLogsError = GetV1TaskByIdLogsErrors[keyof GetV1TaskByIdLogsErrors];

export type GetV1TaskByIdLogsResponses = {
    /**
     * Task logs.
     */
    200: Array<TaskLog>;
};

export type GetV1TaskByIdLogsResponse = GetV1TaskByIdLogsResponses[keyof GetV1TaskByIdLogsResponses];
