// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.yml` | (string & {});
};

export type TaskState = {
    /**
     * The unique identifier for the task.
     */
    id: string;
    /**
     * The timestamp when the task was created.
     */
    created_on: string;
    /**
     * The last action performed on the task.
     */
    last_action: string;
    /**
     * The host running the task.
     */
    runner_host: string;
    /**
     * The current number of retries.
     */
    retries: number;
    /**
     * The maximum number of retries allowed.
     */
    max_retries: number;
    /**
     * The retention period for the task.
     */
    retention: string;
    /**
     * The current status of the task.
     */
    status: string;
    /**
     * The result payload of the task.
     */
    result_payload: string;
};

export type ErrGeneric = {
    error: string;
};

export type ErrField = {
    /**
     * The name of the field that caused the error.
     */
    field: string;
    /**
     * A description of the error related to the field.
     */
    error: string;
};

export type UserResponse = {
    /**
     * The uuid of the user.
     */
    id: string;
    /**
     * The name of the user.
     */
    name: string;
    /**
     * The display name of the user.
     */
    displayName: string;
};

export type UserRequest = {
    /**
     * The uuid of the user to retrieve.
     */
    id: string;
};

export type CreateUser = {
    /**
     * The name of the user to create.
     */
    name: string;
    /**
     * The password for the new user.
     */
    password: string;
    /**
     * The display name for the new user.
     */
    displayName: string;
};

export type PatchUser = {
    /**
     * The uuid of the user to update.
     */
    id: string;
    /**
     * The new name for the user.
     */
    newName?: string;
    /**
     * The new password for the user.
     */
    newPassword?: string;
    /**
     * The new display name for the user.
     */
    newDisplayName?: string;
};

export type PatchMe = {
    /**
     * The new name for the current user.
     */
    newName?: string;
    /**
     * The new password for the current user.
     */
    newPassword?: string;
    /**
     * The new display name for the current user.
     */
    newDisplayName?: string;
};

export type RbacRole = {
    /**
     * The name of the role.
     */
    role: string;
};

export type RbacUserRolesRequest = {
    /**
     * The uuid of the user.
     */
    userId: string;
};

export type RbacPolicy = {
    /**
     * The name of the role. (or "*" for all roles)
     */
    role: string;
    /**
     * The name of the resource group. (or "*" for all resource groups)
     */
    resourceGroup: string;
    /**
     * The allowed permission (e.g., "GET", "POST", "*").
     */
    permission: 'GET' | 'POST' | 'PATCH' | 'DELETE' | 'HEAD' | '*';
};

/**
 * Fully qualified name of an artifact.
 */
export type Fqn = {
    /**
     * The source of the artifact.
     */
    source: string;
    /**
     * The author of the artifact.
     */
    author: string;
    /**
     * The name of the artifact.
     */
    name: string;
};

/**
 * Metadata of an artifact.
 */
export type Artifact = {
    fqn: Fqn;
    /**
     * The version hash of the artifact.
     */
    versionHash: string;
    /**
     * The creation timestamp of the artifact.
     */
    createdAt: string;
    /**
     * The number of times the artifact has been pulled.
     */
    pulls: number;
    /**
     * Tags associated with the artifact.
     */
    tags: Array<string>;
};

export type DeleteUsersUserData = {
    body: UserRequest;
    path?: never;
    query?: never;
    url: '/users/user';
};

export type DeleteUsersUserErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteUsersUserError = DeleteUsersUserErrors[keyof DeleteUsersUserErrors];

export type DeleteUsersUserResponses = {
    /**
     * User deleted successfully. Returns the deleted user.
     */
    200: UserResponse;
};

export type DeleteUsersUserResponse = DeleteUsersUserResponses[keyof DeleteUsersUserResponses];

export type GetUsersUserData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The uuid of the user to retrieve.
         */
        userId?: string;
        /**
         * The name of the user to retrieve.
         */
        name?: string;
    };
    url: '/users/user';
};

export type GetUsersUserErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetUsersUserError = GetUsersUserErrors[keyof GetUsersUserErrors];

export type GetUsersUserResponses = {
    /**
     * Successful response with user information.
     */
    200: UserResponse;
};

export type GetUsersUserResponse = GetUsersUserResponses[keyof GetUsersUserResponses];

export type HeadUsersUserData = {
    body: UserRequest;
    path?: never;
    query?: never;
    url: '/users/user';
};

export type HeadUsersUserErrors = {
    /**
     * Bad request.
     */
    400: unknown;
    /**
     * Unauthorized.
     */
    401: unknown;
    /**
     * Forbidden.
     */
    403: unknown;
    /**
     * User does not exist.
     */
    404: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * Internal server error.
     */
    500: unknown;
};

export type HeadUsersUserError = HeadUsersUserErrors[keyof HeadUsersUserErrors];

export type HeadUsersUserResponses = {
    /**
     * User exists.
     */
    200: unknown;
};

export type PatchUsersUserData = {
    body: PatchUser;
    path?: never;
    query?: never;
    url: '/users/user';
};

export type PatchUsersUserErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * User already exists with the new name.
     */
    409: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PatchUsersUserError = PatchUsersUserErrors[keyof PatchUsersUserErrors];

export type PatchUsersUserResponses = {
    /**
     * User updated successfully.
     */
    200: UserResponse;
};

export type PatchUsersUserResponse = PatchUsersUserResponses[keyof PatchUsersUserResponses];

export type PostUsersUserData = {
    body: CreateUser;
    path?: never;
    query?: never;
    url: '/users/user';
};

export type PostUsersUserErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * User already exists.
     */
    409: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostUsersUserError = PostUsersUserErrors[keyof PostUsersUserErrors];

export type PostUsersUserResponses = {
    /**
     * User created successfully.
     */
    201: UserResponse;
};

export type PostUsersUserResponse = PostUsersUserResponses[keyof PostUsersUserResponses];

export type GetUsersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/list';
};

export type GetUsersListErrors = {
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetUsersListError = GetUsersListErrors[keyof GetUsersListErrors];

export type GetUsersListResponses = {
    /**
     * Successful response with a list of users.
     */
    200: Array<UserResponse>;
};

export type GetUsersListResponse = GetUsersListResponses[keyof GetUsersListResponses];

export type DeleteUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type DeleteUsersMeErrors = {
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteUsersMeError = DeleteUsersMeErrors[keyof DeleteUsersMeErrors];

export type DeleteUsersMeResponses = {
    /**
     * Current user deleted successfully. Returns the deleted user.
     */
    200: UserResponse;
};

export type DeleteUsersMeResponse = DeleteUsersMeResponses[keyof DeleteUsersMeResponses];

export type GetUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetUsersMeErrors = {
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetUsersMeError = GetUsersMeErrors[keyof GetUsersMeErrors];

export type GetUsersMeResponses = {
    /**
     * Successful response with current user information.
     */
    200: UserResponse;
};

export type GetUsersMeResponse = GetUsersMeResponses[keyof GetUsersMeResponses];

export type PatchUsersMeData = {
    body: PatchMe;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type PatchUsersMeErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * User already exists with the new name.
     */
    409: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PatchUsersMeError = PatchUsersMeErrors[keyof PatchUsersMeErrors];

export type PatchUsersMeResponses = {
    /**
     * Current user updated successfully.
     */
    200: UserResponse;
};

export type PatchUsersMeResponse = PatchUsersMeResponses[keyof PatchUsersMeResponses];

export type GetRbacListRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rbac/list-roles';
};

export type GetRbacListRolesErrors = {
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetRbacListRolesError = GetRbacListRolesErrors[keyof GetRbacListRolesErrors];

export type GetRbacListRolesResponses = {
    /**
     * Successful response with a list of roles.
     */
    200: Array<string>;
};

export type GetRbacListRolesResponse = GetRbacListRolesResponses[keyof GetRbacListRolesResponses];

export type DeleteRbacRoleData = {
    body: RbacRole;
    path?: never;
    query?: never;
    url: '/rbac/role';
};

export type DeleteRbacRoleErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * Role is still assigned to users.
     */
    409: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteRbacRoleError = DeleteRbacRoleErrors[keyof DeleteRbacRoleErrors];

export type DeleteRbacRoleResponses = {
    /**
     * Roles deleted successfully.
     */
    200: unknown;
};

export type GetRbacRoleData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The name of the role.
         */
        role: string;
    };
    url: '/rbac/role';
};

export type GetRbacRoleErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetRbacRoleError = GetRbacRoleErrors[keyof GetRbacRoleErrors];

export type GetRbacRoleResponses = {
    /**
     * Successful response with a list of users assigned to the role.
     */
    200: Array<string>;
};

export type GetRbacRoleResponse = GetRbacRoleResponses[keyof GetRbacRoleResponses];

export type HeadRbacRoleData = {
    body: RbacRole;
    path?: never;
    query?: never;
    url: '/rbac/role';
};

export type HeadRbacRoleErrors = {
    /**
     * Bad request.
     */
    400: unknown;
    /**
     * Unauthorized.
     */
    401: unknown;
    /**
     * Forbidden.
     */
    403: unknown;
    /**
     * Role does not exist.
     */
    404: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * Internal server error.
     */
    500: unknown;
};

export type HeadRbacRoleError = HeadRbacRoleErrors[keyof HeadRbacRoleErrors];

export type HeadRbacRoleResponses = {
    /**
     * Role exists.
     */
    200: unknown;
};

export type PostRbacRoleData = {
    body: RbacRole;
    path?: never;
    query?: never;
    url: '/rbac/role';
};

export type PostRbacRoleErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * Role already exists.
     */
    409: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostRbacRoleError = PostRbacRoleErrors[keyof PostRbacRoleErrors];

export type PostRbacRoleResponses = {
    /**
     * Role created successfully.
     */
    201: unknown;
};

export type DeleteRbacUserData = {
    body: {
        /**
         * The uuid of the user.
         */
        userId: string;
        /**
         * The name of the role to remove from the user.
         */
        role: string;
    };
    path?: never;
    query?: never;
    url: '/rbac/user';
};

export type DeleteRbacUserErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteRbacUserError = DeleteRbacUserErrors[keyof DeleteRbacUserErrors];

export type DeleteRbacUserResponses = {
    /**
     * Role removed from user successfully.
     */
    200: unknown;
};

export type GetRbacUserData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The uuid of the user.
         */
        userId: string;
    };
    url: '/rbac/user';
};

export type GetRbacUserErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetRbacUserError = GetRbacUserErrors[keyof GetRbacUserErrors];

export type GetRbacUserResponses = {
    /**
     * Successful response with a list of roles assigned to the user.
     */
    200: Array<string>;
};

export type GetRbacUserResponse = GetRbacUserResponses[keyof GetRbacUserResponses];

export type PostRbacUserData = {
    body: {
        /**
         * The uuid of the user.
         */
        userId: string;
        /**
         * The name of the role to assign to the user.
         */
        role: string;
    };
    path?: never;
    query?: never;
    url: '/rbac/user';
};

export type PostRbacUserErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostRbacUserError = PostRbacUserErrors[keyof PostRbacUserErrors];

export type PostRbacUserResponses = {
    /**
     * Role assigned to user successfully or role was already assigned.
     */
    201: unknown;
};

export type GetRbacListResourceGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rbac/list-resource-groups';
};

export type GetRbacListResourceGroupsErrors = {
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetRbacListResourceGroupsError = GetRbacListResourceGroupsErrors[keyof GetRbacListResourceGroupsErrors];

export type GetRbacListResourceGroupsResponses = {
    /**
     * Successful response with a list of resource groups.
     */
    200: Array<string>;
};

export type GetRbacListResourceGroupsResponse = GetRbacListResourceGroupsResponses[keyof GetRbacListResourceGroupsResponses];

export type DeleteRbacResourceGroupData = {
    body: {
        /**
         * The name of the resource group.
         */
        resourceGroup: string;
    };
    path?: never;
    query?: never;
    url: '/rbac/resource-group';
};

export type DeleteRbacResourceGroupErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteRbacResourceGroupError = DeleteRbacResourceGroupErrors[keyof DeleteRbacResourceGroupErrors];

export type DeleteRbacResourceGroupResponses = {
    /**
     * Resource group deleted successfully.
     */
    200: unknown;
};

export type GetRbacResourceGroupData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The name of the resource group.
         */
        resourceGroup: string;
    };
    url: '/rbac/resource-group';
};

export type GetRbacResourceGroupErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetRbacResourceGroupError = GetRbacResourceGroupErrors[keyof GetRbacResourceGroupErrors];

export type GetRbacResourceGroupResponses = {
    /**
     * Successful response with a list of roles assigned to the resource group.
     */
    200: Array<string>;
};

export type GetRbacResourceGroupResponse = GetRbacResourceGroupResponses[keyof GetRbacResourceGroupResponses];

export type HeadRbacResourceGroupData = {
    body: {
        /**
         * The name of the resource group.
         */
        resourceGroup: string;
    };
    path?: never;
    query?: never;
    url: '/rbac/resource-group';
};

export type HeadRbacResourceGroupErrors = {
    /**
     * Bad request.
     */
    400: unknown;
    /**
     * Unauthorized.
     */
    401: unknown;
    /**
     * Forbidden.
     */
    403: unknown;
    /**
     * Resource group does not exist.
     */
    404: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * Internal server error.
     */
    500: unknown;
};

export type HeadRbacResourceGroupError = HeadRbacResourceGroupErrors[keyof HeadRbacResourceGroupErrors];

export type HeadRbacResourceGroupResponses = {
    /**
     * Resource group exists.
     */
    200: unknown;
};

export type PostRbacResourceGroupData = {
    body: {
        /**
         * The name of the resource group.
         */
        resourceGroup: string;
    };
    path?: never;
    query?: never;
    url: '/rbac/resource-group';
};

export type PostRbacResourceGroupErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * Resource group already exists.
     */
    409: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostRbacResourceGroupError = PostRbacResourceGroupErrors[keyof PostRbacResourceGroupErrors];

export type PostRbacResourceGroupResponses = {
    /**
     * Resource group created successfully.
     */
    201: unknown;
};

export type DeleteRbacEndpointData = {
    body: {
        /**
         * The endpoint to remove from its resource group.
         */
        endpoint: string;
        /**
         * The name of the resource group.
         */
        resourceGroup: string;
    };
    path?: never;
    query?: never;
    url: '/rbac/endpoint';
};

export type DeleteRbacEndpointErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteRbacEndpointError = DeleteRbacEndpointErrors[keyof DeleteRbacEndpointErrors];

export type DeleteRbacEndpointResponses = {
    /**
     * Endpoint removed from resource group successfully.
     */
    200: unknown;
};

export type GetRbacEndpointData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The endpoint to query.
         */
        endpoint: string;
    };
    url: '/rbac/endpoint';
};

export type GetRbacEndpointErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetRbacEndpointError = GetRbacEndpointErrors[keyof GetRbacEndpointErrors];

export type GetRbacEndpointResponses = {
    /**
     * Successful response with the resource group assigned to the endpoint. Empty array if endpoint is not assigned to any resource group.
     */
    200: Array<string>;
};

export type GetRbacEndpointResponse = GetRbacEndpointResponses[keyof GetRbacEndpointResponses];

export type PostRbacEndpointData = {
    body: {
        /**
         * The name of the resource group.
         */
        resourceGroup: string;
        /**
         * The endpoint to assign to the resource group.
         */
        endpoint: string;
    };
    path?: never;
    query?: never;
    url: '/rbac/endpoint';
};

export type PostRbacEndpointErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostRbacEndpointError = PostRbacEndpointErrors[keyof PostRbacEndpointErrors];

export type PostRbacEndpointResponses = {
    /**
     * Endpoint assigned to resource group successfully or was already assigned.
     */
    201: unknown;
};

export type DeleteRbacPolicyData = {
    body: RbacPolicy;
    path?: never;
    query?: never;
    url: '/rbac/policy';
};

export type DeleteRbacPolicyErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteRbacPolicyError = DeleteRbacPolicyErrors[keyof DeleteRbacPolicyErrors];

export type DeleteRbacPolicyResponses = {
    /**
     * RBAC policy deleted successfully.
     */
    200: unknown;
};

export type GetRbacPolicyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rbac/policy';
};

export type GetRbacPolicyErrors = {
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetRbacPolicyError = GetRbacPolicyErrors[keyof GetRbacPolicyErrors];

export type GetRbacPolicyResponses = {
    /**
     * Successful response with a list of RBAC policies.
     */
    200: Array<RbacPolicy>;
};

export type GetRbacPolicyResponse = GetRbacPolicyResponses[keyof GetRbacPolicyResponses];

export type PostRbacPolicyData = {
    body: RbacPolicy;
    path?: never;
    query?: never;
    url: '/rbac/policy';
};

export type PostRbacPolicyErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * One or more fields were invalid.
     */
    404: {
        errors?: Array<ErrField>;
    };
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostRbacPolicyError = PostRbacPolicyErrors[keyof PostRbacPolicyErrors];

export type PostRbacPolicyResponses = {
    /**
     * RBAC policy created successfully.
     */
    201: unknown;
};

export type DeleteArtifactData = {
    body: {
        fqn: Fqn;
        /**
         * Either the version hash or tag of the artifact.
         */
        identifier: string;
    };
    path?: never;
    query?: never;
    url: '/artifact';
};

export type DeleteArtifactErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteArtifactError = DeleteArtifactErrors[keyof DeleteArtifactErrors];

export type DeleteArtifactResponses = {
    /**
     * Artifact deleted successfully. Returns the deleted artifact metadata.
     */
    200: Artifact;
};

export type DeleteArtifactResponse = DeleteArtifactResponses[keyof DeleteArtifactResponses];

export type GetArtifactData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The source of the artifact.
         */
        source: string;
        /**
         * The author of the artifact.
         */
        author: string;
        /**
         * The name of the artifact.
         */
        name: string;
        /**
         * Either the version hash or tag of the artifact.
         */
        identifier: string;
    };
    url: '/artifact';
};

export type GetArtifactErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetArtifactError = GetArtifactErrors[keyof GetArtifactErrors];

export type GetArtifactResponses = {
    /**
     * Successful response with artifact metadata.
     */
    200: Artifact;
};

export type GetArtifactResponse = GetArtifactResponses[keyof GetArtifactResponses];

export type HeadArtifactData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The source of the artifact.
         */
        source: string;
        /**
         * The author of the artifact.
         */
        author: string;
        /**
         * The name of the artifact.
         */
        name: string;
        /**
         * Either the version hash or tag of the artifact.
         */
        identifier: string;
    };
    url: '/artifact';
};

export type HeadArtifactErrors = {
    /**
     * Bad request.
     */
    400: unknown;
    /**
     * Unauthorized.
     */
    401: unknown;
    /**
     * Forbidden.
     */
    403: unknown;
    /**
     * Artifact does not exist.
     */
    404: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * Internal server error.
     */
    500: unknown;
};

export type HeadArtifactError = HeadArtifactErrors[keyof HeadArtifactErrors];

export type HeadArtifactResponses = {
    /**
     * Artifact exists.
     */
    200: unknown;
};

export type DeleteArtifactTagData = {
    body: {
        fqn: Fqn;
        /**
         * The version hash of the artifact to untag.
         */
        versionHash: string;
        /**
         * The tag to remove from the artifact.
         */
        tag: string;
    };
    path?: never;
    query?: never;
    url: '/artifact/tag';
};

export type DeleteArtifactTagErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type DeleteArtifactTagError = DeleteArtifactTagErrors[keyof DeleteArtifactTagErrors];

export type DeleteArtifactTagResponses = {
    /**
     * Tag removed from artifact successfully.
     */
    200: unknown;
};

export type PostArtifactTagData = {
    body: {
        fqn: Fqn;
        /**
         * The version hash of the artifact to tag.
         */
        versionHash: string;
        /**
         * The new tag to assign to the artifact version.
         */
        newTag: string;
    };
    path?: never;
    query?: never;
    url: '/artifact/tag';
};

export type PostArtifactTagErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostArtifactTagError = PostArtifactTagErrors[keyof PostArtifactTagErrors];

export type PostArtifactTagResponses = {
    /**
     * Tag assigned to artifact version successfully.
     */
    201: unknown;
};

export type GetArtifactUploadData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The source of the artifact.
         */
        source: string;
        /**
         * The author of the artifact.
         */
        author: string;
        /**
         * The name of the artifact.
         */
        name: string;
        /**
         * Either the version hash or tag of the artifact.
         */
        identifier: string;
    };
    url: '/artifact/upload';
};

export type GetArtifactUploadErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetArtifactUploadError = GetArtifactUploadErrors[keyof GetArtifactUploadErrors];

export type GetArtifactUploadResponses = {
    /**
     * Successful response with artifact file.
     */
    200: Blob | File;
};

export type GetArtifactUploadResponse = GetArtifactUploadResponses[keyof GetArtifactUploadResponses];

export type PostArtifactUploadData = {
    body: {
        /**
         * The source of the artifact.
         */
        source: string;
        /**
         * The author of the artifact.
         */
        author: string;
        /**
         * The name of the artifact.
         */
        name: string;
        /**
         * Tags to assign to the artifact.
         */
        tag?: Array<string>;
        /**
         * The artifact file to upload.
         */
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/artifact/upload';
};

export type PostArtifactUploadErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * Artifact already exists.
     */
    409: ErrGeneric;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostArtifactUploadError = PostArtifactUploadErrors[keyof PostArtifactUploadErrors];

export type PostArtifactUploadResponses = {
    /**
     * Artifact uploaded successfully.
     */
    201: Artifact;
};

export type PostArtifactUploadResponse = PostArtifactUploadResponses[keyof PostArtifactUploadResponses];

export type GetArtifactListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The source of the artifact.
         */
        source?: string;
        /**
         * The name of the artifact.
         */
        name?: string;
        /**
         * The author of the artifact.
         */
        author?: string;
    };
    url: '/artifact/list';
};

export type GetArtifactListErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The request payload is too large.
     */
    413: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetArtifactListError = GetArtifactListErrors[keyof GetArtifactListErrors];

export type GetArtifactListResponses = {
    /**
     * Successful response with a list of artifact metadata.
     */
    200: Array<Artifact>;
};

export type GetArtifactListResponse = GetArtifactListResponses[keyof GetArtifactListResponses];

export type PostManifestData = {
    body: unknown;
    path?: never;
    query?: never;
    url: '/manifest';
};

export type PostManifestErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * A manifest with the given name already exists.
     */
    409: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type PostManifestError = PostManifestErrors[keyof PostManifestErrors];

export type PostManifestResponses = {
    /**
     * Manifest created successfully.
     */
    201: Blob | File;
};

export type PostManifestResponse = PostManifestResponses[keyof PostManifestResponses];

export type GetTasksListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks/list';
};

export type GetTasksListErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetTasksListError = GetTasksListErrors[keyof GetTasksListErrors];

export type GetTasksListResponses = {
    /**
     * Successful response with task list.
     */
    200: Array<TaskState>;
};

export type GetTasksListResponse = GetTasksListResponses[keyof GetTasksListResponses];

export type GetTasksTaskData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The unique identifier for the task to retrieve.
         */
        id: string;
    };
    url: '/tasks/task';
};

export type GetTasksTaskErrors = {
    /**
     * The request was malformed or invalid.
     */
    400: ErrGeneric;
    /**
     * The provided authentication credentials were invalid.
     */
    401: unknown;
    /**
     * The authenticated user does not have permission to access the requested resource.
     */
    403: unknown;
    /**
     * The requested resource was not found.
     */
    404: ErrGeneric;
    /**
     * An internal server error occurred. Look at the server logs for more details.
     */
    500: unknown;
};

export type GetTasksTaskError = GetTasksTaskErrors[keyof GetTasksTaskErrors];

export type GetTasksTaskResponses = {
    /**
     * Successful response with task information.
     */
    200: TaskState;
};

export type GetTasksTaskResponse = GetTasksTaskResponses[keyof GetTasksTaskResponses];
